import sys

modules = '\n    '.join(sorted(sys.stdin.read().split()))
template = open('ganeti.cabal.in').read()
contents = template.replace('AUTOGENERATED_MODULES_HERE', modules)
sys.stdout.write(contents)
